name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 6 * * *"    # se actualiza 1 vez al día
  workflow_dispatch:         # y puedes lanzarlo a mano desde la pestaña Actions

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: iivanp1
          BRANCH_NAME: "main"
          UTC_OFFSET: -4
          EXCLUDE: ""
          AUTO_PUSH: true
